name: Forest Linden
favicon: null
layout_spectrum: 0.11604
typography_spectrum: 0.4498531185090542
title: Life and living.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#010101'
    - '#cfd0ca'
    - '#bf8e57'
    - '#6a400c'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
